In [ ]:
import numpy

In [ ]:
array1 = numpy.array([1,2,3,4,5,6,11])

In [ ]:
print(array1)

[ 1  2  3  4  5  6 11]


In [ ]:
array2 = numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
type(array2) #type 배열의 타입 

numpy.ndarray

In [ ]:
array2.shape #shape (행,열)배열의 형태 표현 

(4, 3)

In [ ]:
array2.size #size 배열의 요소 갯수 

12

#numpy array 초기값 지정 

In [ ]:
import numpy as np

In [ ]:
array1 = np.full(6,0)
array2 = np.full(6,1) #np.full(갯수, 원하는 값 )
array3 = np.zeros(6 ,int) #np.zeros(원하는 갯수) -> 다 0으로 생성 
array4 = np.ones(6,int) #np.ones(워하는 갯수) -> 다 1로 생성 

print(array1)
print(array2)
print(array3)
print(array4)

[0 0 0 0 0 0]
[1 1 1 1 1 1]
[0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1.]


#랜덤한 값들 생성 

In [ ]:
array1 = np.random.random(6) #np.random.random(갯수) #갯수만큼 랜덤값 생성 0이상 1이하 
print(array1)

[0.23487559 0.39271979 0.82146364 0.0067567  0.74579288 0.97649004]


#연속된 값들이 담긴 numpy array 생성 
##numpy.arange

In [ ]:
array1 = np.arange(6)
array2 = np.arange(2,7) #2부터 7 -1 까지
array3 = np.arange(3,17,3) #3부터 17까지 step 3
print(array1)
print(array2)
print(array3)

[0 1 2 3 4 5]
[2 3 4 5 6]
[ 3  6  9 12 15]


#시각화
##pd.DataFrame

#리스트

In [ ]:
import numpy as np
import pandas as pd

# 리스트를 이용한 시각화 -> 각 행에 카테고리는 안나옴 
# 값이 세로로 나옴 
two_dimensional_list = [['dongwook',50,86],['sineui',89,31],['ikjoong',68,91],['yoonsoo',88,75]]
two_dimensional_array = np.array(two_dimensional_list) #리스트를 np.array 를 통해 numpy array 로 만듦
list_of_series = [
    pd.Series(['dongwook',50,86]),
    pd.Series(['sineui',89,31]),
    pd.Series(['ikjoong',68,91]),
    pd.Series(['yoonsoo',88,75])
]

df1 = pd.DataFrame(two_dimensional_list) #pd.DataFrame(리스트 or 배열 or series) -> 시각화 
df2 = pd.DataFrame(two_dimensional_array)
df3 = pd.DataFrame(list_of_series)

print(f'two_dimensional_list :{df1}')
print(f'two_dimensional_array :{df2}')
print(f'list_of_series :{df3}')


two_dimensional_list :          0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75
two_dimensional_array :          0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75
list_of_series :          0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75


#리스트가 담긴 사전 

In [ ]:
import numpy as np
import pandas as pd

names = ['dongwook','sineui','ikjoong','yoonsoo']
english_scores = [50,89,68,88]
math_scores = [86,31,91,75]
# dictonary를 이용한 시각화 -> 첫행에 각 카테고리 나옴 
dict1 = {
    'name': names,
    'english':english_scores,
    'math_score' : math_scores
}

dict2 = {
    'name': np.array(names),
    'english_score' :np.array(english_scores),
    'math_score': math_scores
}

dict3 = {
    'name': pd.Series(names),
    'english_score' : pd.Series(english_scores),
    'math_score': pd.Series(math_scores)
}

df1 = pd.DataFrame(dict1)
df2 = pd.DataFrame(dict2)
df3 = pd.DataFrame(dict3)

print(df1)
print(df2)
print(df3)


       name  english  math_score
0  dongwook       50          86
1    sineui       89          31
2   ikjoong       68          91
3   yoonsoo       88          75
       name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75
       name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75


#사전이 담긴 리스트 

In [ ]:
import numpy as np
import pandas as pd
# 사전이 담긴 리스트 
my_list = [
    {'name': 'dongwook', 'english_score': 50, 'math_score': 86},
    {'name': 'sineui', 'english_score': 89, 'math_score': 31},
    {'name': 'ikjoong', 'english_score': 68, 'math_score': 91},
    {'name': 'yoonsoo', 'english_score': 88, 'math_score': 75}
]
df = pd.DataFrame(my_list)
print(df)

       name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75


In [ ]:
import pandas as pd

# 코드를 작성하세요.

name = ['Taylor SWift','Aaron Sorkin','Harry Potter','Ji_Sung Park']
birthday = ['December 13,1989','June 9,1961','July 31,1980','February 25,1981']
occupation = ['Singer-songwriter','Screenwriter','Wizard','Footballer']

list = {
    'name' : name,
    'birthday' : birthday,
    'occupation' : occupation
}

# 정답 출력
df = pd.DataFrame(list)
print(df)

           name          birthday         occupation
0  Taylor SWift  December 13,1989  Singer-songwriter
1  Aaron Sorkin       June 9,1961       Screenwriter
2  Harry Potter      July 31,1980             Wizard
3  Ji_Sung Park  February 25,1981         Footballer


In [ ]:
import pandas as pd 
two_dimensional_list = [['HEO',99,80],['YEE',80,76],['YEEM',99,99]]
my_df = pd.DataFrame(two_dimensional_list,columns = ['name','english_score','math_score'])
print(my_df.dtypes)


name             object
english_score     int64
math_score        int64
dtype: object
